# Generated by Django 2.1.1 on 2018-10-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0002_auto_20181010_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
